pool:
  vmImage: 'windows-2019'
trigger:
  batch: true
  branches:
    include:
    - develop
variables:
  Parameters.configuration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(Parameters.configuration)'
name: 2.$(Build.BuildId)$(Rev:.r).0
steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: simon2.keystore
- task: DownloadSecureFile@1
  inputs:
    secureFile: zipalign.bat
- task: NuGetToolInstaller@0
  displayName: 'Install Nuget'
  inputs:
    versionSpec: 4.9.2
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: PwnedPasswords.sln
    restoreDirectory: packages
- task: colinsalmcorner.colinsalmcorner-buildtasks.version-assemblies-task.VersionAssemblies@2
  displayName: 'versionCode'
  inputs:
    sourcePath: PwnedPasswords/PwnedPasswords.Android/Properties
    filePattern: AndroidManifest.xml
    versionSource: variable
    customNumberVariable: Build.BuildId
    versionFormat: custom
    customBuildRegex: '(?:\d+.\d+.\d+.)(\d+)'
    replaceVersionFormat: custom
    customReplaceRegex: 'versionCode="\d+'
    buildRegexIndex: 1
    replacePrefix: 'versionCode="'
- task: colinsalmcorner.colinsalmcorner-buildtasks.version-assemblies-task.VersionAssemblies@2
  displayName: 'versionName'
  inputs:
    sourcePath: PwnedPasswords/PwnedPasswords.Android/Properties
    filePattern: AndroidManifest.xml
    versionSource: variable
    customNumberVariable: Build.BuildId
    versionFormat: custom
    customBuildRegex: '(?:\d+.\d+.\d+.)(\d+)'
    replaceVersionFormat: custom
    customReplaceRegex: 'versionName="1.\d+'
    buildRegexIndex: 1
    replacePrefix: 'versionName="2.'
- task: XamarinAndroid@1
  displayName: 'Build Xamarin.Android'
  inputs:
    projectFile: PwnedPasswords/PwnedPasswords.Android/PwnedPasswords.Android.csproj
    outputDirectory: '$(Build.Repository.LocalPath)/PwnedPasswords/PwnedPasswords.Android/bin/$(Parameters.configuration)'
    configuration: '$(Parameters.configuration)'
    msbuildArchitectureOption: x64
    jdkVersionOption: 1.8
- powershell: |
   $temp = Get-ChildItem $(Build.Repository.LocalPath)\PwnedPasswords\PwnedPasswords.Android\obj\$(Parameters.configuration) | Select name
   Write-host $temp
   $temp = $temp.name
   Write-host $temp
   Write-Output ("##vso[task.setvariable variable=AndroidVer;]$temp")
   Write-host $AndroidVer
  displayName: 'Set Android Version'
- script: '$(Agent.TempDirectory)\zipalign.bat'
  displayName: 'zipalign Script'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: apk'
  inputs:
    PathtoPublish: 'PwnedPasswords/PwnedPasswords.Android/bin/$(Parameters.configuration)/PwnedPasswords.Android-Signed.apk'
    ArtifactName: APK
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: release notes'
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)\release.txt'
    ArtifactName: release