# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  name: 'Hosted VS2017'

variables:
  Parameters.configuration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(Parameters.configuration)'
name: 2.$(Build.BuildId)$(Rev:.r).0
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.2'
  inputs:
    versionSpec: 4.9.2
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: PwnedPasswords.sln
    vstsFeed: '9e24ddbd-3350-4e11-aedd-e8c9af247a4f'
    restoreDirectory: packages      
- task: PowerShell@2
  displayName: 'PowerShell Script build num'
  inputs:
    filePath: PwnedPasswords/PwnedPasswords.UWP/buildnumber.ps1    
- task: colinsalmcorner.colinsalmcorner-buildtasks.version-assemblies-task.VersionAssemblies@2
  displayName: 'Version Assemblies using AndroidManifest.xml'
  inputs:
    sourcePath: PwnedPasswords/PwnedPasswords.Android/Properties
    filePattern: AndroidManifest.xml
    versionSource: variable
    customNumberVariable: Build.BuildId
    versionFormat: custom
    customBuildRegex: '(?:\d+.\d+.\d+.)(\d+)'
    replaceVersionFormat: custom
    customReplaceRegex: 'versionCode="\d+'
    buildRegexIndex: 1
    replacePrefix: 'versionCode="'
- task: colinsalmcorner.colinsalmcorner-buildtasks.version-assemblies-task.VersionAssemblies@2
  displayName: 'Version Assemblies using AndroidManifest.xml'
  inputs:
    sourcePath: PwnedPasswords/PwnedPasswords.Android/Properties
    filePattern: AndroidManifest.xml
    versionSource: variable
    customNumberVariable: Build.BuildId
    versionFormat: custom
    customBuildRegex: '(?:\d+.\d+.\d+.)(\d+)'
    replaceVersionFormat: custom
    customReplaceRegex: 'versionName="1.\d+'
    buildRegexIndex: 1
    replacePrefix: 'versionName="2.'
- task: VSBuild@1
  displayName: 'Build solution PwnedPasswords.sln'
  inputs:
    solution: PwnedPasswords.sln
    configuration: '$(Parameters.configuration)'
- task: XamarinAndroid@1
  displayName: 'Build Xamarin.Android Project PwnedPasswords/PwnedPasswords.Android/PwnedPasswords.Android.csproj'
  inputs:
    projectFile: PwnedPasswords/PwnedPasswords.Android/PwnedPasswords.Android.csproj
    outputDirectory: '$(Build.Repository.LocalPath)/PwnedPasswords/PwnedPasswords.Android/bin/$(Parameters.configuration)'
    configuration: '$(Parameters.configuration)'
    msbuildArchitectureOption: x64
    jdkVersionOption: 1.8
- task: DownloadSecureFile@1
  inputs:
    secureFile: zipalign.bat
- powershell: |
   Copy-Item -Path $(Agent.TempDirectory)\PwnedPasswords.UWP_StoreKey.pfx -Destination $(Build.Repository.LocalPath)\PwnedPasswords\PwnedPasswords.UWP\PwnedPasswords.UWP_StoreKey.pfx
- task: DownloadSecureFile@1
  inputs:
    secureFile: PwnedPasswords.UWP_StoreKey.pfx
- task: VSBuild@1
  displayName: 'Build solution PwnedPasswords.UWP'
  inputs:
    solution: PwnedPasswords/PwnedPasswords.UWP/PwnedPasswords.UWP.csproj
    vsVersion: 15.0
    msbuildArgs: '/p:AppxBundlePlatforms="x86" /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppxPackages\\" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
    platform: x86
    configuration: '$(Parameters.configuration)'
- powershell: |
   $temp = Get-ChildItem $(Build.Repository.LocalPath)\PwnedPasswords\PwnedPasswords.Android\obj\$(Parameters.configuration) | Select name
   Write-host $temp
   $temp = $temp.name
   Write-host $temp
   Write-Output ("##vso[task.setvariable variable=AndroidVer;]$temp")   
   Write-host $AndroidVer   
  displayName: 'PowerShell Script'
- task: DownloadSecureFile@1
  inputs:
    secureFile: simon2.keystore
- script: '$(Agent.TempDirectory)\zipalign.bat'
  displayName: 'Command Line Script'
- task: richardfennellBM.BM-VSTS-GenerateReleaseNotes-Task.Generate-Release-Notes.GenerateReleaseNotes@2
  displayName: 'Generate release notes'
  inputs:
    outputfile: $(Build.ArtifactStagingDirectory)\release.txt
    templatefile: template.txt
- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     PwnedPass.Test\bin\Debug\*.Test.dll
     !**\*TestAdapter.dll
     !**\obj\**    
- task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@18
  displayName: 'WhiteSource Bolt'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: apk'
  inputs:
    PathtoPublish: 'PwnedPasswords/PwnedPasswords.Android/bin/$(Parameters.configuration)/PwnedPasswords.Android-Signed.apk'
    ArtifactName: APK  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: release notes'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\release.txt'
    ArtifactName: release   
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact: UWP'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\AppxPackages'
    ArtifactName: UWP