# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  vmImage: 'windows-2019'
trigger:
  batch: true
  branches:
    include:
    - develop
variables:
  Parameters.configuration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(Parameters.configuration)'
name: 2.$(Build.BuildId)$(Rev:.r).0
steps:
- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: 'GitHub connection 2'
    repositoryName: funkysi1701/PwnedPass
    tagSource: manual
    tag: '2.$(Build.BuildId).1.0'
    title: 2.$(Build.BuildId).1.0 Beta
- task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@18
  displayName: 'WhiteSource Bolt'
- task: richardfennellBM.BM-VSTS-StyleCop-Task.Stylecop-Runner.StyleCop@2
  displayName: 'StyleCop'
  inputs:
    treatStyleCopViolationsErrorsAsWarnings: true
    detailedSummary: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: stylecopsummary'
  inputs:
    PathtoPublish: '$(build.StagingDirectory)/stylecopsummary.md'
    ArtifactName: stylecopsummary