# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  name: 'Hosted VS2017'
trigger:
  batch: true
  branches:
    include:
    - beta
variables:
  Parameters.configuration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(Parameters.configuration)'
name: 2.$(Build.BuildId)$(Rev:.r).0
steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: simon2.keystore
- task: DownloadSecureFile@1
  inputs:
    secureFile: zipalign.bat
- task: DownloadSecureFile@1
  inputs:
    secureFile: PwnedPasswords.UWP_StoreKey.pfx
- task: NuGetToolInstaller@0
  displayName: 'Install Nuget'
  inputs:
    versionSpec: 4.9.2
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: PwnedPasswords.sln
    restoreDirectory: packages
- task: PowerShell@2
  displayName: 'build num'
  inputs:
    filePath: PwnedPasswords/PwnedPasswords.UWP/buildnumber.ps1
- task: colinsalmcorner.colinsalmcorner-buildtasks.version-assemblies-task.VersionAssemblies@2
  displayName: 'versionCode'
  inputs:
    sourcePath: PwnedPasswords/PwnedPasswords.Android/Properties
    filePattern: AndroidManifest.xml
    versionSource: variable
    customNumberVariable: Build.BuildId
    versionFormat: custom
    customBuildRegex: '(?:\d+.\d+.\d+.)(\d+)'
    replaceVersionFormat: custom
    customReplaceRegex: 'versionCode="\d+'
    buildRegexIndex: 1
    replacePrefix: 'versionCode="'
- task: colinsalmcorner.colinsalmcorner-buildtasks.version-assemblies-task.VersionAssemblies@2
  displayName: 'versionName'
  inputs:
    sourcePath: PwnedPasswords/PwnedPasswords.Android/Properties
    filePattern: AndroidManifest.xml
    versionSource: variable
    customNumberVariable: Build.BuildId
    versionFormat: custom
    customBuildRegex: '(?:\d+.\d+.\d+.)(\d+)'
    replaceVersionFormat: custom
    customReplaceRegex: 'versionName="1.\d+'
    buildRegexIndex: 1
    replacePrefix: 'versionName="2.'
- task: VSBuild@1
  displayName: 'Build Android.csproj'
  inputs:
    solution: PwnedPasswords\PwnedPasswords.Android\PwnedPasswords.Android.csproj
    configuration: '$(Parameters.configuration)'
- task: XamarinAndroid@1
  displayName: 'Build Xamarin.Android'
  inputs:
    projectFile: PwnedPasswords/PwnedPasswords.Android/PwnedPasswords.Android.csproj
    outputDirectory: '$(Build.Repository.LocalPath)/PwnedPasswords/PwnedPasswords.Android/bin/$(Parameters.configuration)'
    configuration: '$(Parameters.configuration)'
    msbuildArchitectureOption: x64
    jdkVersionOption: 1.8
- powershell: |
   $temp = Get-ChildItem $(Build.Repository.LocalPath)\PwnedPasswords\PwnedPasswords.Android\obj\$(Parameters.configuration) | Select name
   Write-host $temp
   $temp = $temp.name
   Write-host $temp
   Write-Output ("##vso[task.setvariable variable=AndroidVer;]$temp")
   Write-host $AndroidVer
  displayName: 'Set Android Version'
- script: '$(Agent.TempDirectory)\zipalign.bat'
  displayName: 'zipalign Script'
- powershell: |
   Copy-Item -Path $(Agent.TempDirectory)\PwnedPasswords.UWP_StoreKey.pfx -Destination $(Build.Repository.LocalPath)\PwnedPasswords\PwnedPasswords.UWP\PwnedPasswords.UWP_StoreKey.pfx
  displayName: 'copy pfx files'
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: PwnedPasswords.sln
    msbuildArgs: '/p:AppxBundlePlatforms="x86|x64|ARM" /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\AppxPackages\\" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload'
    configuration: '$(Parameters.configuration)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: apk'
  inputs:
    PathtoPublish: 'PwnedPasswords/PwnedPasswords.Android/bin/$(Parameters.configuration)/PwnedPasswords.Android-Signed.apk'
    ArtifactName: APK
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: release notes'
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)\release.txt'
    ArtifactName: release
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact: UWP'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\AppxPackages'
    ArtifactName: UWP