# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  name: 'Hosted VS2017'
trigger:
  batch: true
  branches:
    include:
    - master
pr: none
variables:
  Parameters.configuration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(Parameters.configuration)'
name: 2.$(Build.BuildId)$(Rev:.r).0
steps:
- task: whitesource.ws-bolt.bolt.wss.WhiteSource Bolt@18
  displayName: 'WhiteSource Bolt'
- task: richardfennellBM.BM-VSTS-StyleCop-Task.Stylecop-Runner.StyleCop@2
  displayName: 'StyleCop'
  inputs:
    treatStyleCopViolationsErrorsAsWarnings: true
    detailedSummary: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: stylecopsummary'
  inputs:
    PathtoPublish: '$(build.StagingDirectory)/stylecopsummary.md'
    ArtifactName: stylecopsummary